name: Update Cloudflare IPs

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 解决权限问题

      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: pip install requests beautifulsoup4

      - name: 🚀 Run scraper
        run: python cf-ip-scraper.py

      - name: 💾 Commit changes
        if: steps.git_diff.outputs.change_found == 'true'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Auto-update Cloudflare IPs"
          git push

      - name: 🔍 Check changes
        id: git_diff
        run: echo "change_found=$(git status --porcelain | grep -q 'README.md' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
